name: Send Out Mailing List Emails

on:
    push:
        branches:
            - master

permissions:
    contents: write

jobs:
    build-and-deploy:
        name: Build And Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Determine If Email Should Be Sent
              id: check-email
              run: |
                  if git diff --name-only HEAD^ HEAD | grep -q "^src/components/ice-cream/flavors.ts$"; then
                      echo "Flavors File Changed"
                      echo "send_email=true" >> $GITHUB_OUTPUT
                  else
                      echo "No Changes to Flavors File"
                      echo "send_email=false" >> $GITHUB_OUTPUT
                  fi

            - name: Send Email
              if: steps.check-email.outputs.send_email == 'true'
              run: curl -X POST https://api.maxrosoff.com/send-email
