name: Build and Deploy to Pages

on:
    push:
        branches:
            - master

permissions:
    contents: write

jobs:
    build-and-deploy:
        name: Build And Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version-file: ".nvmrc"

            - name: Cache Node Modules
              uses: actions/cache@v4
              id: cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install Node Modules
              run: npm install

            - name: Build Site
              run: npm run build-website

            - name: Deploy Site
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist
