name: Build and Deploy to Pages

on:
  push:
    branches: [master]

jobs:

  build-and-deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Node Modules
        run: npm install

      - name: Build Site
        run: npm run build

      - name: Deploy Site
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
