name: Build and Deploy to Pages

on:
  push:
    branches: [ master ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
            persist-credentials: false

      - name: "Install Node Modules"
        run: npm install

      - name: "Build Site"
        run: npm run build

      - name: "Deploy Site"
        uses: johno/actions-push-subdirectories@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            args: dist mrrosoff Personal-Website-Built-For-Pages
